### ISSUE TITLE
Error thrown when relationship is not registered

### ISSUE THREAD

**Issue by Istanful** [danivek/json-api-serializer#129] opened 2021-08-30 08:58 UTC
## Description

When a resource is deserialized and the included relationship is not registered an error will be thrown. The error says `Cannot read property 'schema' of undefined`, which does not help a whole lot to troubleshoot.

To help the user my suggestion is to throw an error saying:
> No relationship named [relationshipKey] registered on [type]

This would break backwards compability though, since some tests will fail.

What is the desired behavior here? I'm happy to patch it given how you want it to work.

Here's a test to reproduce:

```javascript
    it('should throw an error when relationship is not registered', (done) => {
      const Serializer = new JSONAPISerializer();
      Serializer.register('article');
      Serializer.register('people');

      const data = {
        data: {
          id: '1',
          type: 'article',
          relationships: {
            author: {
              data: {
                type: 'people',
                id: '1'
              }
            }
          }
        },
        included: [
          {
            type: 'people',
            id: '1'
          }
        ]
      };

      expect(function () {
        Serializer.deserialize('article', data);
      }).to.throw(Error, 'No relationship named author registered on article');
      done();
    });

```

**Comment by danivek** [comment] 2021-09-14 09:35
Should be fixed by #126

**Comment by Istanful** [comment] 2021-09-16 06:05
@danivek I don't think so. In my example the author _relationship_ is not registrered. In his example it is. I haven't looked into the code just now, but I do remember several tests failing when I created a similar fix.

Can you reopen the issue?

As I mentioned I'm happy to create a fix, given how you want it to work.

**Comment by danivek** [comment] 2021-09-16 08:33
@Istanful I tried with your unit test and now with master/2.6.4, the error returned is now `No type registered for people`.

Please provide another test case, if you think the issue is not resolved.

**Comment by danivek** [comment] 2021-09-16 12:27
@Istanful To avoid breaking things actually, what about not throwing error and trying to deserialize with the given type if it is registered.

**Comment by Istanful** [comment] 2021-09-16 12:51
@danivek Sure. If you think that's the more correct behaviour then I think avoiding breakage is a good idea. 👍 😄

**Closed** 2021-09-23 09:52 UTC
